### ISSUE TITLE
Create API Lupa Password

### ISSUE THREAD

**Issue by alpinmohsa541** [FinPro-ITPerbankan2023/FinPro-MyCuan#44]
- Permintaan Reset Password:

> Pengguna memasukkan alamat email mereka pada halaman yang sesuai.
> Sistem mengirim permintaan reset password ke server melalui API.

- Verifikasi Email:

> Server memeriksa apakah alamat email yang diberikan oleh pengguna ada dalam basis data sistem.
> Jika email tersebut valid, sistem akan melanjutkan proses reset password.

- Generate Token Reset Password:

> Server akan menghasilkan token unik yang akan digunakan sebagai tanda pengenal untuk mengidentifikasi permintaan reset password yang terkait dengan email tersebut.

- Kirim Email dengan Tautan Reset Password:

> Server mengirim email ke alamat email pengguna yang berisi tautan khusus yang mengandung token yang dihasilkan sebelumnya. Tautan ini akan mengarahkan pengguna ke halaman untuk mengatur ulang kata sandi.

**Comment by ikrar557** [comment]
close dengan PR #50
