### ISSUE TITLE
Create Page lupa Password

### ISSUE THREAD

**Issue by alpinmohsa541** [FinPro-ITPerbankan2023/FinPro-MyCuan#45]
Halaman lupa password ini berisikan masukan email dan konfirmasi lupa password

![Image](https://github.com/FinPro-ITPerbankan2023/FinPro-MyCuan/assets/55131607/4432f8af-0c5b-4269-b54d-f187d2df56a3)

![Image](https://github.com/FinPro-ITPerbankan2023/FinPro-MyCuan/assets/55131607/283a565d-3b8c-4abd-8557-587260e2ed04)

**Comment by ikrar557** [comment]
close dengan PR #50
