### ISSUE TITLE
API Profil pemberi dana

### ISSUE THREAD

**Issue by alpinmohsa541** [FinPro-ITPerbankan2023/FinPro-MyCuan#56]
Profile ini berisi tentang user
- Nama
- NIK
- Nomor tlpn
- email
- dan ubah foto profile

![Image](https://github.com/FinPro-ITPerbankan2023/FinPro-MyCuan/assets/55131607/779d7d45-9e4d-49ac-b3c2-3857d629dfd7)

**Comment by ikrar557** [comment]
close dengan PR #81
