### ISSUE TITLE
API Daftar Pemberi dana

### ISSUE THREAD

**Issue by alpinmohsa541** [FinPro-ITPerbankan2023/FinPro-MyCuan#59]
API ini berisikan : 
- Email
- Password
- konfirmasi password
- no hp
- Nama Lengkap
- NIK

![Image](https://github.com/FinPro-ITPerbankan2023/FinPro-MyCuan/assets/55131607/5c2c3566-374a-45e3-abe2-f34a510e5d94)

**Comment by ikrar557** [comment]
close issue to PR #60
